version: '3'
services:
    db:
        env_file: 
            - .env
        image: postgres
        volumes: 
            - postgresql-data:/var/lib/postgresql/data/pgdata
        ports:
            - 5432:5432
    web:
        build: .
        ports:
            - 4880:4880
        depends_on:
            - db

volumes:
    postgresql-data: